### ISSUE TITLE
CU6

### ISSUE THREAD

**Issue by gaenroca** [equipossl/PruebaMod4_SSL#1]
Prueba de Liidchard 

https://app.lucidchart.com/invitations/accept/ea8b236b-2bee-47ee-bbf5-4ae4e7811917

**Comment by gaenroca** [comment]
Prueba 2 Lucidchart

**Comment by anduribe** [comment]
se ve ok, tamos

**Comment by itate32** [comment]
Bien Gabriel !

**Comment by gaenroca** [comment]
![image](https://user-images.githubusercontent.com/60945095/85816460-5e387a80-b739-11ea-8760-5281c162627d.png)

**Comment by itate32** [comment]
Buena !
